version: '3.5'

services:
  mysql:
    container_name: mysql_container
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      TZ: 'Europe/Paris'
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-time-zone=Europe/Paris',
      ]
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
